export const SET_CHANNEL_ID = "SET_CHANNEL_ID";

export const START_SEARCH_VIDEOS = "START_SEARCH_VIDEOS";
export const SEARCH_VIDEOS_SUCCESS = "SEARCH_VIDEOS_SUCCESS";
export const SEARCH_VIDEOS_ERROR = "SEARCH_VIDEOS_ERROR";

export const PLAY_NEXT_VIDEO = "PLAY_NEXT_VIDEO";
export const ADD_VIDEO_TO_PLAYLIST = "ADD_VIDEO_TO_PLAYLIST";
export const CHANGE_VIDEO_POSITION = "CHANGE_VIDEO_POSITION";

export const START_FETCH_PLAYLIST = "START_FETCH_PLAYLIST";
export const FETCH_PLAYLIST_SUCCESS = "FETCH_PLAYLIST_SUCCESS";
