export const START_FETCH_VIDEOS = "START_FETCH_VIDEOS";
export const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS";
export const FETCH_VIDEOS_ERROR = "FETCH_VIDEOS_ERROR";

export const PLAY_NEXT_VIDEO = "PLAY_NEXT_VIDEO";
export const ADD_VIDEO_TO_PLAYLIST = "ADD_VIDEO_TO_PLAYLIST";
