export const SET_CHANNEL_MASTER = "SET_CHANNEL_MASTER";

export const START_SEARCH_VIDEOS = "START_SEARCH_VIDEOS";
export const SEARCH_VIDEOS_SUCCESS = "SEARCH_VIDEOS_SUCCESS";
export const SEARCH_VIDEOS_ERROR = "SEARCH_VIDEOS_ERROR";

export const PLAY_NEXT_VIDEO = "PLAY_NEXT_VIDEO";
export const ADD_VIDEO_TO_PLAYLIST = "ADD_VIDEO_TO_PLAYLIST";
export const REMOVE_VIDEO_FROM_PLAYLIST = "REMOVE_VIDEO_FROM_PLAYLIST";
export const CHANGE_VIDEO_POSITION = "CHANGE_VIDEO_POSITION";

export const START_FETCH_CHANNEL = "START_FETCH_CHANNEL";
export const FETCH_CHANNEL_SUCCESS = "FETCH_CHANNEL_SUCCESS";

export const FETCH_PLAYLIST_SUCCESS = "FETCH_PLAYLIST_SUCCESS";

export const START_AUTH = "START_AUTH";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";
export const SOCKET_AUTH = "SOCKET_AUTH";
export const SUBSCRIBE_TO_CHANNEL = "SUBSCRIBE_TO_CHANNEL";
export const UNSUBSCRIBE_FROM_CHANNEL = "UNSUBSCRIBE_FROM_CHANNEL";
